# This rule is not used by the project test-operator-4-5-2 itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants permissions to create, update, and delete resources within the ship.my.domain.
# This role is intended for users who need to manage these resources
# but should not control RBAC or manage permissions for others.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: test-operator-4-5-2
    app.kubernetes.io/managed-by: kustomize
  name: frigate-editor-role
rules:
- apiGroups:
  - ship.my.domain
  resources:
  - frigates
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ship.my.domain
  resources:
  - frigates/status
  verbs:
  - get
