# This rule is not used by the project test-operator-4-5-2 itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to ship.my.domain resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: test-operator-4-5-2
    app.kubernetes.io/managed-by: kustomize
  name: frigate-viewer-role
rules:
- apiGroups:
  - ship.my.domain
  resources:
  - frigates
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ship.my.domain
  resources:
  - frigates/status
  verbs:
  - get
