# This rule is not used by the project test-operator-4-5-2 itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over ship.my.domain.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: test-operator-4-5-2
    app.kubernetes.io/managed-by: kustomize
  name: frigate-admin-role
rules:
- apiGroups:
  - ship.my.domain
  resources:
  - frigates
  verbs:
  - '*'
- apiGroups:
  - ship.my.domain
  resources:
  - frigates/status
  verbs:
  - get
