name: Alpha Update

permissions:
  contents: write
  issues: write
  pull-requests: write

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 2" # Every Tuesday at 00:00 UTC

jobs:
  alpha-update:
    runs-on: ubuntu-latest
    env:
      BRANCH_NAME: kubebuilder-alpha-update-${{ github.run_number }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        fetch-depth: 0
    
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: stable

    - name: Install Kubebuilder
      run: |
        echo "Building Kubebuilder from fork (open-pr-issue-flags)..."
        git clone --depth 1 --branch open-pr-issue-flags \
          https://github.com/vitorfloriano/kubebuilder.git /tmp/kubebuilder
        cd /tmp/kubebuilder
        make build
        sudo cp bin/kubebuilder /usr/local/bin/
        echo "Kubebuilder built and installed successfully"
        kubebuilder version
        rm -rf /tmp/kubebuilder

    - name: Run kubebuilder alpha update
      run: |
        kubebuilder alpha update \
        --squash \
        --preserve-path .github/workflows \
        --force \
        --open-pr \
        --open-issue