name: Alpha Update

permissions:
    contents: write
    pull-requests: write
    actions: write

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 2" # Runs every Monday at 00:00 UTC

jobs:
    alpha-update:
      runs-on: ubuntu-latest

      steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 'stable'

      - name: Install Kubebuilder
        run: |
          curl -L -o kubebuilder "https://go.kubebuilder.io/dl/latest/$(go env GOOS)/$(go env GOARCH)"
          chmod +x kubebuilder
          sudo mv kubebuilder /usr/local/bin/
      
      - name: Configure Git
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
      
      - name: Run kubebuilder alpha update
        run: |
          set -e
          kubebuilder alpha update --from-version v4.5.2 --force
      
      - name: Extract versions from merge commit
        run: |
          # Get the last commit message (alpha update final commit)
          COMMIT_MSG=$(git log -1 --pretty=format:"%s")
          echo "Final commit message: $COMMIT_MSG"
          
          # Extract versions from commit message
          versions=($(echo "$COMMIT_MSG" | grep -oE 'v[0-9]+\.[0-9]+\.[0-9]+'))
          FROM_VER="${versions[0]:-unknown}"
          TO_VER="${versions[1]:-unknown}"
          
          echo "PR_FROM_VERSION=$FROM_VER" >> "$GITHUB_ENV"
          echo "PR_TO_VERSION=$TO_VER" >> "$GITHUB_ENV"
          echo "Detected versions: $FROM_VER -> $TO_VER"
      
      - name: Restore workflows directory
        run: |
          git restore --source=main --staged --worktree .github/workflows
          git add .github/workflows
          git commit --amend --no-edit || true
      
      - name: Soft reset last 4 commits and checkout main
        run: |
          git reset --soft HEAD~4
          git checkout main
      
      - name: Push changes and create Pull Request
        run: |
          # Create and push branch
          git checkout -b kubebuilder-alpha-update
          git push origin kubebuilder-alpha-update --force
          
          # Create PR using GitHub API
          gh api \
            --method POST \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            /repos/${{ github.repository }}/pulls \
            -f title="chore: update Kubebuilder scaffolding from ${{ env.PR_FROM_VERSION }} to ${{ env.PR_TO_VERSION }}" \
            -f body="Automated Kubebuilder scaffolding update from ${{ env.PR_FROM_VERSION }} to ${{ env.PR_TO_VERSION }}. Please review the changes." \
            -f head="kubebuilder-alpha-update" \
            -f base="main"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}